Fix test failures, extract common hypothesis givens
Fixes the following error from hypothesis in the unit tests on macOS:

```
FAILED dorado/scheduling/tests/test_earth_limb.py::test_observer_on_surface - FloatingPointError: Got allow_subnormal=True, but we can't represent subnormal floats right now, in violation of the IEEE-754 floating-point specification.  This is usually because something was compiled with -ffast-math or a similar option, which sets global processor state.  See https://simonbyrne.github.io/notes/fastmath/ for a more detailed writeup - and good luck!
```